CREATE SEQUENCE SQ_MICRO_USUARIO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TB_MICRO_USUARIO(
    ID_USUARIO INTEGER DEFAULT SQ_MICRO_USUARIO.NEXTVAL NOT NULL PRIMARY KEY,
    NOME_USUARIO VARCHAR2(100) NOT NULL,
    EMAIL_USUARIO VARCHAR2(100) NOT NULL UNIQUE,
    SENHA_USUARIO VARCHAR2(100) NOT NULL,
    DATA_CADASTRO DATE DEFAULT SYSDATE,
    FUNCAO_USER VARCHAR2(30) DEFAULT 'USER'
);

